= Krasina
:author: Marcos Cruz (programandala.net)
:revdate: 2020-11-04
:toc:
:toc-title: Contenete/Content

// This file is part of project
// _Krasina_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 202011040102

// Interlingue {{{1
== Interlingue

// Pri ti projecte {{{2
=== Pri ti projecte

Scope:: Crear un libre digital in EPUB e altri formates de _Krasina_,
un rakonta original in Interlingue, scrit de Jan A. Kajš in 1938, quel
esset ja digitalisat de Bedŕich Plavec secun li textu original e
convertet de Thomas Schmidt in formate PDF in 2013.

Autor:: Marcos Cruz, 2019, 2020.

Web-loc:: http://ne.alinome.net[ne.alinome.net].

// Qualmen constructer li libre {{{2
=== Qualmen constructer li libre

Si vu ne posse atender li liberation del sequente version, vu self
posse constructer li libre-documentes.

In prim, ples confirmar que li programas listat in li section
"Requirements" (besones) del document <Makefile> es instalat in vor
sistema.

Tande ples intrar li documentiere del projecte e comandar `make` secun
ti exemples:

|===
| Comande    | Efecte

| make       | Constructer li formates recomandat
| make all   | Constructer omni formates
| make azw3  | Constructer li AZW3
| make dbk   | Constructer li DocBook
| make epub  | Constructer li EPUB (omni variantes)
| make epuba | Constructer li *EPUB per Asciidoctor EPUB3 (recomandat)*
| make epubd | Constructer li EPUB per dbtoepub (sin covriment)
| make epubp | Constructer li EPUB per Pandoc
| make epubx | Constructer li EPUB per xsltproc (equivalent a dbtoepub)
| make odt   | Constructer li OpenDocument
| make pdf   | Constructer li PDF (ambi grandores)
| make pdfa4 | Constructer li *PDF de grandore DIN A4 (recomandat)*
| make pdfl  | Constructer li PDF de grandore «letter»
|===

Li documentes es creat in li documentiere <target>.

// Nómines del documentes final {{{2
=== Nómines del documentes final

Quande omni documentes final es constructet (talmen anc contenet in e li
liberaturas che GitHub e li archives descargabil ex
http://ne.alinome.net[ne.alinome.net]), li contenete del documentiere <target>
es ti:

- krasina.adoc._a4.pdf
- krasina.adoc._letter.pdf
- krasina.adoc.dbk
- krasina.adoc.dbk.dbtoepub.epub
- krasina.adoc.dbk.pandoc.epub
- krasina.adoc.dbk.pandoc.odt
- krasina.adoc.dbk.xsltproc.epub
- krasina.adoc.epub

Li nómines es self-explicatori: Ili indica li operation de conversion
de formates ex li documente fontal de
http://asciidoctor.org[Asciidoctor], li convertores usat e li
variantes de stil o grandore por li formates final (DocBook, EPUB,
OpenDocument e PDF). Ultra to, ti convention nominal prevente futur
colisiones de nómines, si plu convertores o formates vel esser
adjuntet al projecte.

////
// XXX OLD --
NOTE: Tri convertores es usat por constructer li documentes EPUB. Tis
constructet per dbtoepub e xsltproc es virtualmen identic, ma ambi es includet
por possibil beson. Fórsan alcun ex li tri variantes functiona plu bon in Vor
libre-letor.
////

// English {{{1
== English

// Abouth this project {{{2
=== Abouth this project

Goal:: Make an e-book in EPUB and other formats of _Krasina_, an
original story in Interlingue, written by Jan A. Kajš in 1938, which
was already digitalized by Bedŕich Plavec after the original text and
converted into PDF format by Thomas Schmidt in 2013.

Author:: Marcos Cruz, 2019.

Website:: http://ne.alinome.net[ne.alinome.net].

// How to build the book {{{2
=== How to build the book

If you cannot wait for the release of the next version, you can build
the target files yourself.

First, make sure the programs listed under the "Requirements" section
of the <Makefile> file are installed in your system.

Then enter the project's directory and give the `make` command as
follows:

|===
| Command    | Effect

| make       | Build the *recommended formats*
| make all   | Build all formats
| make azw3  | Build the AZW3
| make dbk   | Build the DocBook
| make epub  | Build the EPUB (all variants)
| make epuba | Build the *EPUB with Asciidoctor EPUB3 (recommended)*
| make epubd | Build the EPUB with dbtoepub (no cover page)
| make epubp | Build the EPUB with Pandoc
| make epubx | Build the EPUB with xsltproc (equivalent to dbtoepub)
| make odt   | Build the OpenDocument
| make pdf   | Build the PDF (both sizes)
| make pdfa4 | Build the *PDF (DIN A4 size) (recommended)*
| make pdfl  | Build the PDF (letter size)
|===

The documents are built in the <target> directory.

// Names of the target files {{{2
=== Names of the target files

When all target files are built (as included in the GitHub releases and in the
corresponding archives downloadable from
http://ne.alinome.net[ne.alinome.net]), the contents of the <target> directory
are the following:

- krasina.adoc._a4.pdf
- krasina.adoc._letter.pdf
- krasina.adoc.dbk
- krasina.adoc.dbk.dbtoepub.epub
- krasina.adoc.dbk.pandoc.epub
- krasina.adoc.dbk.pandoc.odt
- krasina.adoc.dbk.xsltproc.epub
- krasina.adoc.epub

The names are self-explanatory: They indicate the format conversion
process from the http://asciidoctor.org[Asciidoctor] source document,
the converters used and the style or size variants of the final
formats (PDF, DocBook, EPUB and OpenDocument). Beside, this naming
convention prevents name clashes in the future, if more tools or
formats are added to the project.

////
// XXX OLD --
NOTE: Three converters are used to build the EPUB files. Those built
by dbtoepub and xsltproc are virtually identical, but both of them are
included just in case. Perhaps some of the three variants gives better
results on your reader.
////
