= Krasina: Original raconta ex li subterrania de Moravian Carst
:author: Jan A. Kajš

// This file is part of project
// _Krasina_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 201903241615

Printería de J. A. Kajš

Brno 1938.

== Anteparol

Til nu noi incontra ancor mult homes ne credent que on posse usar un lingue
constructet anc in li literatura. On asserte nos que un lingue artificial es un
"`homunculus`" sin propri vive. Noi dat nos li pena demonstrar li
usabilitá de nor lingue per traductiones. Ma on objectiona nos que li
traductiones ne refuta li cardinal objection, it es que li lingue self ne have
su propri vive e posse esser solmen un plu o minu perfect gramofon del lingues
natural. Nu, mem un natural lingue es un tal gramofon de homan pensa. Por
demonstrar que Occidenal posse haver mem original literatura, yo ha resoluet
scrir un raconta in ti-ci lingue. In quant yo ha successat, deve judicar li
letores, nam yo self ne have li ambicie har creat un ovre maestral, nam yo ne
es un literator, ni artist inspirat.

Yo usa simplic stil sin ornamentes por esser comprendet anc del novicios in
Occidental.

Mi calid desir es que plu competent scritores mey reprender mi iniciative,
que ili mey crear ovre digni del sublim idé del interlingue.

Jan A. Kajš

NOTE: Li textu di ti-ci edition esset digitalisat de Bedŕich Plavec secun li
textu original e convertet de Thomas Schmidt in li formate PDF.

== Li avigilation de Ondra

Ondra esset avigilat per du fosforescent ocules fixat a su visage. Con pena
il apertet li ocules e in li demí-luce il vide super se un inclinat cape. Il
efortia sedentar se, ma li manus, apartenent a ti inconosset ente, presse le
retro.

"`Jace, jace, tu es malad,`" il audi un inconosset voce.

Quo ha accidet le? Ti voce, benque plen de tendresse e compassion, ne
apartene a su matre. Il leva li cap por vider plu bon qui inclina se super le.
Il vide un particulari inconosset visage de quel li trates indica que it
apartene a un femina. Ma, qui es ti femina e qualmen ella apari ci? Il pena
soluer ti problema, ma li cerebre ne vole servir le, li cap es quam vacui e
obtusi...

E li inconosset femina fortia le jacer tranquilmen; ella palpat su contuset
membres, sur alcun locos su fingres halta e Ondra senti un brulant dolore. Poy
ella invelopa le in un pelisse e da le trincar alqual acerbi decocte. Ondra
trinca e strax indormi quam un infant con li sentiment que super le vigila un
potent e afabil ente.

Quande il avigilat se denove, il sentit se plu bon. Li corpore adver dolet
ancor, il esset ancor sin forties, ma li strangi pression sur li cerebre ja ha
desaparit, tam que il ja posset reflecter.

U il es? Esque li mysteriosi ente ne esset un chimere? O esque it esset
solmen un strangi somnie? Ma no, il ya es invelopat in un pelisse quel ne
apartene le e circum se il vide solmen roccas e super se petrin vulte con milles
de stalactitin formationes. Quam un fulmine aparit in su mente li rememore a
su braconal aventura e su cade...

Yes, it es talmen, li erra es excludet. It trova se in li subterrania del
Carste...

== Un braconal aventura de Ondra

Toník Ondra havet li fama de un originalo. Il evitat li societé e su liber
tempore il passat con libre o per vagada in li natura. In li forestes de
Moravian Carst il conosset chascun rocca e caverne, ta il trapassat chascun
fissura e audaciat mem penetrar in li dangerosi grottes, u ja pluri homes
perdit li via e poy cadet in alcun precipitie e ruptet li nuc.

In su biblioteca on trovat un pelmel atestant li manca de un metode in li
selection li selection de letura. On posset trovar ta libres de Clifton, de
Karl May, de Verne, de Emerson, libres naturscientic, historic, filosofic,
theologic, politic e linguistic. Il leet omnicos venient in su manus, ma poy il
ha fixat se a libres filosofic e linguistic.

Su duesim amore esset li fusil. Ma ti esset "`su secret amore`". Il ne
posset
confesser it publicmen, nam il ne havet li jure de chasse ni li passport por
portar li fusil. Ma forsan to esset li cause que su amore al fusil tam crescet
que alcunvez il sucumbet in tentation e surtit in nocte al braconage. Pri ti su
surtidas savet solmen su matre quel chascunvez audit li craca del porta, quande
il abandonat li domette.

"`Ea necú, Toník,`" ella avertit le unvez quande il prendet li clinc,
"`yo have alqual presentiment que alquo mal va incontrar te. Resta hem,
almen hodíe.`"

"`Eh, quo posse incontrar me? Yo es ya caut. Li forestes yo conosse bon
e hodie es just li max oportun tempe. It prepara se a un storm e li
gardaforestes va esser celat. Esse si cuida. Adio matre, dormí bon.`" E
Ondra surtit ex li domette con li fusil celat sub li mantel.

Pro cautie il braconat solmen in li forestes plu distant. Pos un hor de
energic marcha il sedentat se sur li margine de un clariera e atendet con li
fusil sur li genú, preparat a tirar. Interim li vente ha acrescet e li fulmines
trasectet li obscur firmament. In li rebrillia de fulmine il perceptet un
capreol current tra li clariera. Un fulmine exeat del fusil e li detonation
mixtet se con li tonnere. Ondra ha lansat se a su victime sur li clariera, ma
in li sam tempore il audit un menaciant "`Halt`"!

Haltar? Lassar se capter? No, to ne esset in intentiones de Ondra! Il ha
lassat li capreol jacer e per quelc saltes il ha atinget li foreste, u inter li
arbores il esset plu secur contra li balles. Il precipita se adavan, ma detra
se il audi li menaciant "`Halt! o yo va tirar!`"

Ondra neglige li avertiment e curre ad avan. Su persecutor trumpeta e ne
lontan responde su compan. Per diabol! Ondra senti li dangere. Il save que li
braconage es severmen punit. Versimilmen it es ancor un rest del servage, del
tempore quande li chasse esset reservat por li nobilité, Si on va capter le, il
ne va escapar li prison. Quel honte il vell causar a su old matre! Il deve
escapar, pro to ad avan! Omni su forties il mette in li muscules de su gambes e
curre quasi pariante con li vente. Ma anc persecutores ne reposa e ili expense
omni forties por capter le. Talmen li chasse durat presc un demí-hor quande
Ondra mispassuat ye un radica. In su maleol un crac e il senti que il ne posse
escapar. Con pena il atinget li apertura de un proxim caverne. Li max extrem
tempore, nam li persecutores es ja in su talones. Il ja audi li passus avan li
caverne. Li passus halta...

"`Il ya ne posse esser lontan, it ha semblat me que il claudica,`" dit
un del persecutores.

"`Forsan il ha celat se in alcun caverne ci,`" adjunte li altri.

"`Noi posse strax explorar it, nam it es solmen sac-fores.`"

Ondra senti li frissone. It es li fine, il ne va escapar. Silentmen il pussa
se al max extrem angul del caverne e presse al frigid mur... Li persecutores in
li strett proximitá. Subitmen Ondra senti que li suol move se e il glissa a
bass; in comensa il glissa lentmen ma con acceleration. Quelc chocas e Ondra ne
plu senti alcun timore, il evanesce...

== Che li Slavines

Un pian canta aproximant se finit li considerationes de Ondra. Il ja
percepte singul paroles quel apare le alqual conosset. De ú il conosse les? Ah,
il ja save, ili es tam simil al antiqui slavic a quel lingue il dedicat mult
vesperes, quande li tempe ne permisset le vagar in li forest. O, quam
interessant es li studies lingual.

Li cant ha cessat e avan le stat su salvatora. Quande su ocules acustomat se
al particulari luce, quel semblat penetrar in li subterrania tra diversi
fissuras, il discernet li conturas del feminin statura e poc e poc il posset
vider passabilmen bon. Ella ha esset vestit per ursin pelisse e sur li pedes
havet sandales ornat per fibules de ursin dentes. Anc su vestiment ne indiget
ornamentes e to esset por Ondra un atest pri li artistic facultá del juvena. Ti
constatation pro cause inexplicabil, ha injoyat le e quande ella prendet su
manu por auxiliar le levar se, percurret le un electric scintille e plenat le
per un dulci sentiment, til nu inconosset.

Li juvena ductet le tra zigzagant coridores quel strax astrettat se talmen
que on posset solmen con pena passar tra ili, strax ili elargat se in magnific
temples ornat de milliones de annus per fabulosi figuras de stalactites. Ti
spectacul tentat Ondra a haltar e revar pri li marveles e miracules del natura.
Ma li quida fortiat le avansar, assertente le que existe mem plu bell temples in
su patria.

Li juvena babilla, questiona e talmen Ondra aprende que ella es Krasina,
filia del chef del Slavines queles vive sur li rive de un fluvie.

Ondra ja ha perceptet li murmura del fluvie e sones de canzon in li lingue
de su quida. Quande ili aproximat se, salutat les un grand bruida. It semblat
que li trumpetada ye cornes de uros e li tamburada ne va haver li fine. Ma
quande se levat un oldo, omni silentat se. Krasina chuchotat a Ondra: "`To
es mi patre.`"

Ondra sentit qualmen omni ocules perfora le por decovrir su intentiones.

"`Qui es tu?`" questiona li oldo.

"`Yo es Toník Ondra e yo labora in li proxim ferral fonderia.

`"Quo significa ferral fonderia?"`

`"Quo es forne e quo li ferrin protometall?"`

Ondra ha conceptet que ti gente have null idé pri li ferrin cultura; pro to
il efortiat explicar les quo es li protometall e a quo servi li ferre e stal.
Quande il ha volet demonstrar, quo posse far un fusil, il ha rememorat que it
es alcú incombrat e que il deve serchar it. Krasina, quel esset constantmen ye
su flanc, ha ofertat se acompaniar le in li serchada, ma li chef, benque self
suficent curiosi, ha decidet que ti cose ne urge.

Un grand astonament evocat li horlogette de Ondra. It eat de un manu al
altri. Chascun volet
palpar ti marvel del munde. Li questionada `"qualmen?"`, `"pro
quo"` e `"por quo"` ne havet li fine. Li explication esset penibil,
nam Ondra adver ha comprendet li questiones, ma responder in un foren lingue,
in quel on nequande ha parlat, ne es facil. Ondra devet reflecter chascun
parol, corecter se o li tchec paroles adaptar al lingue antiqui-slavic. Solmen
ci il reconosset li diferentie inter li passiv e activ saventie del lingue.
Ondra comprendet li lingue del Slavines, ma parlar lor lingue il posset solmen
con pena. Il va besonar ancor un poc de exercicie.

Quande li unesim ataca de questiones un poc ha cessat, Ondra posset un poc
circumspecter. Li camp del Slavines esset sur li rive de un subterran fluvie.
Li tendas esset fat de pelles de urses e uros. Sur un liber loc flammeat un foy
de ligne quel esset aportat del fluvie e de osses antediluvial quel trovat se
in abundantie in li grottes.

Krasina ne posset detraer su ocules de Ondra. Durant li festine, arangeat al
honore de Ondra, ella presentat le li maxim grass boccades, quo il quittat per
grat regardes.

Krasina esset de mediocri altore con musculos brasses e bell-format gambes.
In li visage de livid colore, sub larg fronte, brilliat du verdatri ocules
queles, astonantmen, regardat suavi e calidmen.

Ondra ha esset surprisat per li aspect de ti grottal gente. Il imaginat se
li troglodytes con plat fronte e salient guancial osses, durantque il vide ci
li formes de cranies pri queles null cultural popul vell dever hontar. Li chef
ha finit li festine per un prega in quel il mersiat li Patre por lu bon e ver
figurat per nutrimentes quel li Slavines recive in suficent quantitá. Ondra ha
esset denove surprisat: Quo have li manjage e trincage comun con lu bon e ver?
In li proxim ocasion Krasina deve explicar ti enigma.

Li chef volet ear a su lette, ma secun li demande de Ondra il narrat,
qualmen su popul ha venit sub li Carst.

It esset ante mult cent e cent annus, quande un slavin familie celat se in
un grotte por assecurar se contra nomadic asiatic tribes. Ti familie havet con
se quelc agnes e canes. Ma anteque it posset abandonar li refugia, li plafon
del grotte ha ruit e barrat li exeada. Li familie esset inprisonat. Felicimen
it esset in un principal coridore e on posset avansar.

Li Slavines ha trovat un apt loc por resider sur li rive de fluvie quel ili
nominat Ponikva. Ti nomine nullmen surprisat Ondra, nam il savet que li
novi-formation Punkva di necos. Ponikva significa `"submergeant aqua"`.
It proveni del antiqui-slavic lingue e li radica `"nikat"` conservat se
ancor in quelc paroles tchec. Noi vell nullmen cuidar pri que li Slavines nomina
Punkva altrimen, ma li linguistic marotte de Ondra obtenet un satisfation.

Li fluvie furnit les li aqua e aportat ligne por mantener li foy. Lor ocules
adaptat se al obscuritá talmen que ili videt suficent bon anc in ti medie,
secun quel format se lor tot vive.

Li agnes pastet se sur scarsi herbage sur li rive del fluvie. Por lor
securitá stat li canes quel avisat li dangere menaciant al agnes. Ti dangere
representat li grottal ursos quel esset in li subterrania tre mult. Ti bestie
furnit al Slavines li carne, li pellisse por vestimentes, li dentes e griffes
por ornamentes.

Li table del Slavines esset simplic. Un apart plante, simil al asparge e
crescent sur li rive de Ponikva, compleet li carne de uros, ursos, agnes e
pisces. Li sal esset substituet per cindre. Ma
con li tempore li agnes perdit li fecunditá e poc a poc diminue se talmen
que ili va desaparir. Li sam aparentie on posse constatar anc pri li uros de
quel resta solmen un micri quantité.

Li letura e scritura es che li Slavines inconosset, almen secun nor usa.
Solmen in li pictura ili es versat, quam atestat diversi dessines per carbon,
sur li roccas e gravuras sur ossin e petrin utensiles e vases.

Mill-annual tradition, anxiosmen mantenet, di que lor ancestres esset pastores e cultivatores de vegetales de quel on fa pane. Ili self nequande videt li pane, ma ili crede que li pane es li optim nutriment del hom.

Ili have anc lor propri religion. Ili crede al Patre sin li comense e fine --
sin li nascentie e morte -- quel mantene li munde per li foy e aqua, per li
amore juntet con li sagesse e veritá. Omni quo circuma les have un symbolic
sense. Li aqua significa li veritá quel purifica, renova e fa trincar al anim
homan. Li calore significa li amore quel intertene li vive fysic e spiritual.
Li luce ilumina li intelectu, da li sagesse. Li petre significa li veritá del
crede. Li agnello significa li innocentie, li mild animales significa li bon e
li feroci besties li mal inclinationes del hom. Ili crede in li vive eterni in
quel on intra per li morte, it es per li deposition del fysic corpore. Li morte
es li porta per quel on passa del fysic in li spiritual munde, del visibil in
li invisibil munde. Li dormida da nos alqual imagination pri ti transition. Li
nucleo del religion es li amore. Deo es li sagesse e li amore, pro to haver li
ver religion significa amar lu bon e lu ver. Amar li fonte del amore -- li Patre
e con il amar omni su infantes.

Ti simplic religion da les tant materie por meditation que lor rason es tre
developat e lor cordie nequande desira dominar, nam li amore ducte a servir li
proximo.

Li etá del Slavines es relativmen curt -- admaxim quinant annus. Lor numere
ne augmenta se, nam alcun families es sin infantes. Li eterni Patre talmen
cuida por que lor numere ne superpassa li condition del existentie.

Ili ne conosse li guerres, nam ili forma un tribe. Politica, li national e
religiosi conflictes es che ili inconosset. Ili combatte solmen con li urses e
uros. Ma anc ti combattes es por ili symboles de combattes con lor propri mal
inclinationes. Ti combattes pro manca de apt armes es sovente plen de dangere e
pro to ne manca les ni heroes.

On posse presc dir que li Slavines vive exter li tempore. Ili ne es avigilat
per aurora o per canta de gallinos, ni per fabrical sirenes. Li tempore indica
les solmen li marea de Ponikva. Li hores e minutes ne have por ili alcun
importantie, nam ili ne besona timer pri tard ariva in li buró o ovreria. Ili
have tam mult tempore que it ha cessat esser lor sclavator. E si es ver li
proverbie: `"li tempor es moné"`, tande ili es li max rich popul del
munde.

== Ondra contraveni un habitu

==  del Slavines

Krasina esset un excellent instructora de Ondra. Ella acompaniat le partú e
narrat le per quo li Slavines ocupa se. In li proxim ocasion Ondra eat a
serchar li perdit fusil. Si il va trovar it, il va partiprender in chasse del
grottal mannes e va demonstrar les quo posse far li fusil. E li fortune favorat
le. Li fusil-tube salit ex li sand apu li loc u Krasina ha trovat le. Plenat de
joy il inbrassat li yuna e ante que ella posset reconscier, il ha presset sur
su labies un long besa. Li labies de ella aspirat se al suis, ma strax poy ella
ha liberat se de su inbrassament e comensat amarimen plorar.

Ondra ne posset comprender quo ha accidet la. Il efortiat consolar la, ma
quande il provat inbrassar la denove, ella forcurret con singlutada. Ondra
devet usar omni eloquentie por quietar la tant que ella posset explicar le quo
ha accidet tam horribil. Per su act Ondra tam desdignat la que ella ne posse
con bon conscientie revenir a su tribe. Solmen li puella have li jure besar li
mann quel ella vole maritar. Tal es li habitu del Slavines.

`"Esque vermen ne existe escape de ti mal situation?"` questionat li
contrit Ondra.

`"Ne existe, ne existe, ne existe!"`

`"Esque ne exculpa nos mi ignorantie de vor mores?"`

`"Inter nos veni nequi ignorant nor mores."`

`"To es vermen fatal... Ma, atende, Krasina. Esque tu ne ha dit que
solmen li puella posse besar li mann quel ella ha selectet?"`

`"Yes, to yo ha dit. It es talmen e in to jace nor malfortun,"`
respondet Krasina con resignation.

`"Esque tu ne comprende, mi cordiette, que in to es nor
salvation?"`

`"Qualmen it vell esser possibil?"` Krasina fixat a Ondra su ocules in
quel manifestat se li surpris e dubita.

`"To es ya tre simplic cose... Tu ha ya besat me li unesim e poy yo ha
besat te. Esque tu vermen ha obliviat to?"`

Krasina esset stupefat per surpris, ma bentost ella reconsciet e jettat se
al pectore de Ondra e besat le, besat e ridet quam li turtur.

`"Ho, tu es filú, Toník! Filú, filú, filú! Ma tu va esser punit. Krasina
va esser tui marita!"`

`"Tu vell desirar, Krasina?"`

`"Certmen, Krasina vole. Ma tu, Toník? Esque tu ne va regretar tui
decision? Esque tu va acustomar se a nor subterran vive? O esque tu ne va fugir
quande tu va trovar li via ex li
subterrania e lassar Krasina ci in grive?"`

`"Krasina, mi anim, da me besa!"`

Krasina besa e denove besa Toník por atestar que ella vole esser su marita
e
Toník reciproca li besas quam pruva que il consenti con li election. Poy
Toník ha jettat li fusil sur li epol e prendet Krasina ye li manu. Ili retornet
quam petulant infantes, gaymen cantante.

Quande ili ha arivat al camp, Krasina levat li manu quam signe que ella have
alquo por dir al tribe. Poy ella stantat se sur li puntas del pedes e trivez
besat Ondra quo il ha reciprocat. Li yunos quel in van solicitat li favore de
Krasina, ha jettat li fulmines del ocules, ma submisset se al ancian more.
Krasina ha selectet su marito.

Li old chef presentat a Ondra li manu e parlat long a su tribe. Ondra ha
captet de ti parlada que il va esser li chef del tribe, pro que Valdomir ne
have filio.

Li feminas aclamat e li mannes acceptat li decision con tonnerant hurrá!

Quande ili ha suficent criat, ili resoluet que deman on va ear al chasse por
procurar carne por li nuptial festine.

== Li grand chasse

In li sequent die Ondra ha esset avigilat per grand tumultu. Li mannes
preparat se al chasse. In un moment il ha levat se. Il ha lavat se in li frigid
fluvie, prendet li fusil e stantat se in li range de chasseros. E vi un
eveniment inaudit: Krasina stantat se apu Ondra e volet acompaniar le al
chasse. To ha evocat inter li chasseros un murmur de inconsens, ma li chef ha
dit que ha aparit un nov circumstantie e pro to on posse admisser anc ti ci
particularitá.

Li batte sur li tambur esset li signe al departe. Li truppe avansat sin
parol.

Quande ili arivat a un colossal grotte, li truppe ha dislocat se e li chef
desligat su cane. Ti ha lansat se in un angul del grotte de u resonat un
menaciant murmur. Li chasseros esset tendet quam li cordes de violine. Strax
poy aparit un enorm urso atacant li aboyant cane. Li max proxim chassero ha
brandisset su petrin clobb por un mortal colpe. Ma tande accidet alquo pri quo
li chasseros long poy parlat. Per ti fort brandissement li chassero perdit li
equilibrie e cadet in un precipitie. Li urso atacat li chef quel stat max
proxim. Ti dat al urso un fort colp. Ma ti colp tamen ne ha suficet e li
furiosi bestie ha captet in su pattes li chef plu tost quam il posset dar li
duesim colp per su clobb. Li bestie comensat tornar se con su victime e li
chasseros ne audaciat batter it por ne atinger lor chef.

Tande venit li moment quande Ondra posset monstrar li efect del fusil quel
til tande esset misapreciat del indigenes. Ondra ha apuntat li arme: Eclatat li
foy e detonation, li bestie ha rugit e
volet lansar se a Ondra. Menaciosmen gruniente li urso balansat a Ondra. Ma
tande Ondra tirat denove, e li bestie cadet al terra. Li chasseros con hurrá
battet li urso.

Li old chef quel escapat li dangere sin alqual accidente, declarat que li
tribe ne posset desirar plu bon chef quam va esser ti quel Krasina selectet
quam marito. E Krasina, fieri ye su Toník, intonat li heroic canzon quel on
cantat solmen quande alcun mann fat se celebri per un heroic acte.

Interim li chasseros ha apertet li bestie per lor primitiv culteles, depellat
e dissectet it e retornat al camp. Li feminas esset astonat per tam celebri
retorn del mannes, ma quande ili aprendet qui ha contribuet a ti bon success,
unes comensat apretar li pelle por li tenda del nov pare, durantque li altres
preparat manjages por li nuptial festine.

== Li nuptial ceremonie

It ha monstrat se que li chef esset anc li prestre de su tribe. Il ha
prendet un ceremonial vestiment sur quel ha esset pictet diversi evenimentes ex
li vive del tribe. Ondra ha devet aconosser que su nov popul es dotat per
fantasie in grand mesura.

Li cornist ha dat li signe pos quel li sponses devet desvestir se e insaltar
li aqua. Poy ili, tenente se ye un manu, per li altri devet svimmar contra li
fluentie del fluvie. Ili inmerget se in li aqua quel esset tam frigid que Ondra
claccat li dentes.

Interim Valdomir ha fat li foy sur un lapid e reverentiante a omni lateres,
il exclamat: `"Auxila nos, ó Patre!"`

Pos to li sponses surtit del aqua e strax esset invelopat in calid pelisses
e quar infantes ductet les al prestre. Ti ha prendet li cordie del urso, trivez
elevat it, reverentiat ad omni lateres e posit it sur li foy. To ha esset li
signale al canta quel ha intonat li mannes. Li sense de ti canzon esset
circa:

[verse]
--
Ó spiritu sin comense e fine,
spiritu sin nascentie e morte,
spiritu imensi in fortie,
spiritu constant in amore.
a te noi sacrifica nor cordies,
a te noi consacra nor vives,
e anc ti ci yun pare.
--

Li sponses declinat li capes, li tambures sonat. li prestro ha cupat un
bucle de capilles del sponses, plectet it e jettat in li foy. Pos to on
cantat:

[verse]
--
Lor capilles, del fortie li symbole,
ci in foy nu ha unit se.
--

Li prestro fat li benedition, juntet li manus del sponse quam signe de
reciproc sucurse. Ili trivez besat li terra e per to li ceremonies ha
finit.

Pos li finition del ceremonies omni sedentat se al nuptial festine.

Festine! Li letor imagina se grand tables covrit per blanc toales, sur li
tables buquetes, circum li tables stules, current servitores con platiles,
servietes, brilliant servises e li ceteri pompe, indispensabil che li
potentates. Quam stupefat il vell esser, si il vell sedentar se al festine che li
chef del Slavines!

Li chef sedet sur ursin pelle e li ceteres sur li suol. Li cocinera hachat
por chascun un pezze de carne e dat it in li manu. Li furca esset viceat per
fingres e li cultel per dentes.

Pos li carne sequet li sup contenent alqual subterran plante. Li sup esset
cocinat in petrin vases e manjat per ossin coclares. Li festine ha finit per
`"foyosi aqua"` quel on fat ex li radicas del sam plante. Plu tard Ondra
ha aprendet que on nomina ti plante `"pane"`. E vermen, it esset lor
pane, nam ultra li carne it esset lor unic nutriment.

Al fine li musicantes demonstrat lor arte. Lor max perfect instrumentes
esset li tambures e li trumpetes; ti ci dominat in li symfonic concerte. Ondra
adver ne comprendet bon quo li musica vole expresser, nam il esset inter li
Slavines solmen curt tempore, ma malgré to il sentit que it have plu intim
relation al vive quam li modern musica del popules con tot altri conditiones
del vive.

Ho, quam il regretat que il ne manua alcun musical instrument! Ma -- esque li
grottal popul vell comprender su musica? Esque it vell comprender su hymne pri li
sole, pri li flores, susurrada del vente e cante de avies?

Certmen it ne vell comprender. Ma -- esque li circumitá ne va lansar Ondra in
li primitivisme? Esque il ne percepte ja nu quam passu pos passu il fusiona con
su nov popul? Yes, il senti que il ama su popul ne solmen quam li chef, ma quam
un de it. Il va dar se li pena por esser bon consiliator de su popul. Adver il
es yun, ma il senti li fortie por su nov tache. Pro to in li music-<br/>pause
il demandat silentie por posser dir quelc paroles. Li tambures sonat. Poy Ondra
in su alocution dit circa lu sequent:

`"Mi amicos e fratres! Secun li consilie de vor potent e sagi chef
Valdomir vu ha electet me quam su successor. Yo ne posse promesser vos alquo
grandios, nam yo es ancor extran inter vos. Yo
ancor ne conosse bon vor vive, vor customes e mores e pro to it es anc
possibil que in li comense yo quelcvez va peccar contra vor leges. Ma in tal
casus ples memorar que it ne es fat con intention, ma solmen de inconossentie.
Quo yo posse promesser vos, es lu sequent: Li tot amore quel mi cordie es
capabil, yo va dar a mi popul. Omni conossenties queles yo ha aquisitet supra,
yo vole dar vos. Yo va efortiar que almen parte del aquisitiones del modern
tempe, queles li homanité super nos usa, deveni anc vor proprietá. Yo es pret
viver e morir por vos."`

Ti alocution, benque fat in defectos lingue de Slavines, evocat un grand
entusiasme. Li tamburada ne volet cessar e Ondra esset circumat de mannes
volent far con le li sanguin fratrinitá.

Poy sequet danses, in plupart danses figural, danses de quel ha originat
mani populari danses tchec -- almen Ondra pensat to.

Por contribuer al general gaudie, il ha cantat quelc populari canzones
tchec, de quel `"U es mi hem?"`, `"Moravia"` e `"Flue aqua
frigid"` il devet repetir quelcvez. Il devet promesser docer les omni
canzones quel il conosse.

Quande li festa ha finit, quar yunos portat li nov-marites sur ursin pelisse
in li novi tenda.

== Ondra quam preceptor

Strax li sequent die pos li nuptie Ondra ha anunciat que il va docer li
letion e scition e ha invitat omni Slavines partiprender in li aprension. Omni
ha venit essente curiosi pri ti novitá. Ondra ha explicat quel importantie have
li scritura por li homes in supra u on printa diversi libres e jurnales, u es
exchangeat lettres inter homes tre distant li un del altri. Por li Slavines to
posse haver solmen limitat importantie, pro que ili ne have li paper ni li
possibilitá printar libres. Ili tamen posse comodmen lassar informationes in li
camp, si ili vell forear, ili posse scrir lor comunicationes sur li roccas.
Malgré ti litt usabilitá del scrition, omni Slavines ha aprobat li decision de
Ondra.

Ondra ha prendet un carbon e scrit sur un lapid: `"Valdomir"` e poy
descomposit li parol in singul litteres e denove juntet li sylabes til que omni
ha capit li miracul. Poy il ha invitat Valdomir a scrir self sui nomine. Ti
procedura esset penibil, ma tamen li old chef ha successat con grand joy. Poy
Ondra scrit li nomines comensant per V, A, L, D etc. Chascun esset fieri que in
li unesim lecion il ha aprendet scrir su nomine.

Secun ti metode Ondra continuat chascun die quelc hores. Bentost il videt
que inter li max diligent eleves excelle su Krasina. Li joy del eleves crescet
chascun die e pos quelc leciones ili posset leer li canzones quel Ondra scrit e
cantat.



== Li explorativ via

`"Krasina, mi culumbetta, esque tu vole acompaniar me in un viage? Yo
desira inspecter mi imperia,"` dit Ondra a su yun marita.

`"Con plesur, Toník. Noi va preparar li proviant e deman va ear ad ú tu
va desirar."`

Li sequent die ili ha plenat un valise per proviant, quel Ondra ha fixat a
su dorse e prendente li fusil ili startat.

In li comense ili eat tra coridores conosset, ma poy ili eat tra fores, tra
quel ili apen posset perpresser se. Ili eat ad supra e ad infra u ante
millenies penetrat li aqua. Ili arivat in grottes con plafones covrit per magnific
stalactites. Maniloc li stalagmites ha format un forest. In pluri grottes li
paretes splendet per sorciatri cascades de stalactites. Ondra haltat perplex
avan li ovre del natura.

Quant millenies li natura laborat por far ti magnificentie?

In altri grottes ili trovat stalactites formant fantastic figuras de nanes,
cortnes, vases, calices e divers objectes por li homan fantasie. Un altri
grotte presentat li image de destruction. Ta li plafon con pesant stalactites
ha ruit e nu omnicos jace sur li terra in un caos. Ma vice li ruit stalactites
forma se novi -- quam un image del circulant vive...

Ondra ha resoluet reposar ci un poc.

Pos li manja, quel pos penosi marcha bon sapet, Ondra ha petit Krasina,
racontar alquo pri li psychic vive de Slavines. E Krasina, injoyat per su
interesse pri li spiritual coses, racontat que li hom es un spiritu quel vive
in un fysic corpore e simultanmen in li munde spiritual. Li corpor es limitat
per li spacie, ma li spiritu vive exter li spacie, pro to noi posse esser in un
moment in quelcunc loc.

Ondra ha translocat se in spiritu a su nativ dom e parlat con su matre quel
esset plen de timore pri su unic filio.

`"Yes, it es talmen, Krasina,"` afirmat Ondra, `"just yo ha
convictet me pri to."`

`"Qualmen, Toník?"`

`"Yo ha translocat me spiritualmen a nor dom, a mi mamá, quel ja deplora
me."`

`"Esque tu ama tui matre, Toník?"`

`"Yes; forsan pro que ella es tam bon."`

`"It es rect. Si noi ama lu bon, noi ama max mult li bon homes. To pro lu
bon quel es in ili."`

`"To es acceptabil explication. E nu, esque tu posse dir me, quo doce vor
religion pri li
matrimonie?"`

`"Tui question tre joya me. Nor religion doce que li maritage es li
juntion de lu bon (li amore) con lu ver (li sagesse). Li femina representa li
principie del amore e li mann li principie del sagesse. Noi save que li amore
es figurat in li fysic munde per calore e li veritá per luce. Li tot vive es
conditionat per calore e luce, ergo per amore e sagesse. Sin li amore e sagesse
li ver matrimonie es inpossibil sammen quam li fysic vie es inpossibil sin li
calore e luce.

"`Yo deve confesser que yo nequande serchat un tal profundore in li
religion. Tam minu yo vell expectar it che un popul separat durant millennies de
nor cultura.

`"Tu deve raconar me pri vor religion. Precipue in quo it difere de
nor."`

`"Car Krasina, til nu yo ha audit solmen un parte de vor religion. Ma ja
ti litt fragment sufice me por abandonar mi actual religion e adherer a vor.
Che nos existe quelc principal religiones e chascun have quelc sectes."`

`"Qualmen it es possibil, Toník? Esque vu ne crede a un Deo?"`

`"Noi crede, ma chascun eclesie explica Le altrimen. Ma pri to yo va
parlar altrivez. In ti ci media, precipue in ti ci miracules del natura, plu
bon incade tui religion. Damage, que yo ancor ne ha penetrat in vor symbolica
por posser leer in tri ci temple, quo ha scrit li natura durant millennies e
sci ancor hodie."`

`"Tu deve petir mi patre, il posse explicar te omnicos. Il es versat anc
in li coses composit quam es ti ci lapides. Me atraet til nu precipue li coses
simplic."`

`"Yo ne posse prender to in mal. Che nos apen li decesim yuna in tui etá
vell posser presentar tal spiritual coses talmen quam tu es capabil far
it."`

`"Esque tu ha tam bon conosset vor yunas?"`

`"Forsan mem ne. Ma ti queles yo ha conosset plu bon, aparet tro
superficial, pro to yo preferet evitar las."`

`"It es possibil que tu es injust contra ili. Yo di to malgré que tu ha
selectet me."`

`"Tu es bon e sagi, Krasina. Con te yo certmen va far alquo por nor
popul. Yo tre desira ducter it al luce por que ili mey joyar pri omni marveles
del natura ta supra. Forsan noi va successar trovar un via quel va ducter nos
ex li subterrania."`

`"It es bell, Toník, que tu pensa a nos. Ma, esque noi ne vell esser ta
supra quam extranes? Esque noi va posser viver per nor propri vive? sque ta
supra noi ne va esser in plu grand labyrint quam ci?"`

`"Tui inquietation ne es sin base. Vor simpli vive certmen have su
avantages pri quel vu apen save. Ma malgré to yo vell preferer esser con te in
li regne del sole e flores. In liber hores yo vell promenar con te in forestes u
noi vell escutar li susurrada del vente, cante del avies e burdonament del apes.
Noi vell colier bell flores e far de ili corones por te. Noi vell luder in li
brillie del sole quam petulant infantes.

"`Cessa ja, Toník! Tant nov e inconosset coses yo ne posse capir in un
vez. Yo nequande ha videt flores. Yo ne save quo es un avie, quo es un ape e
forest. Tu deve explicar me omnicos. Ma yo time que yo vermen va desirar
abandonar mi patria quel yo ama in sam gradu quam tu ama li tui.`"

"`Bon. Ma tu oblivia que vor patria es ta supra. Ci vu es solmen
prisonat. Mi patria es tui patria, de tot tui popul quel habitat Moravia ante
millennies.`"

"`Forsan tu es rect. Ma tu deve parlar pri to con mi patre ca il va voler
abandonar li prison, qualmen tu nomina nor patria.`"

"`Con plesur yo va parlar e persuader le. Solmen si noi va trovar li via
a supra. Yo opine que li majorité va ear con nos. Si ili ne va voler exear, noi
va visitar les ci e aportar les diversi coses. Ma yo crede que multes va exear
pro curiositá e poy ne va voler retornar. Ma nu noi ja deve continuar nor
explorativ via.`"

== Li inundation

"`Aqua! Aqua! Aqua!`"

Ti clamation avigilat Ondra de profund dormida pos li penosi e van vagada in
li coridores. Il ha demettet li pellissin covritura de se e ha excurret del
tenda por aprender quo ha accidet. In li camp eset un grand tumultu. Li feminas
curret ci e ta, li infantes criat e li mannes colectet li necessi objectes. It
aproxima se li aqua quel probabilmen va inundar li inferiori tuneles e
grottes.

Ondra ha vocat Krasina e eat consultar Valdomir. Ti esset ja parat al
departe. Il explicat a Ondra que alquande li fluvie deborda se e inunda omni
coridores circum li camp. Ultimvez it ha evenit ante quelc annus. Li aqua ha
plenat li grottes super li altore del mann. Li coridores ne suficer por capir
li masses del aqua quel constantmen montat. Quelc homes perit durant li fugida.
Nu it es necessi far omni assecurativ preparationes.

Valdomir, benque il formalmen transdat li duction a Ondra, tamen til nu
esset aconosset quam autoritá e il self ne posset acustomar se a un subordinat
rol. Pro to il ha ordonat preparar se al fugida.

Hante prendet li utensiles e armes, ili departet.

Avan li convoy curret li canes, detra les Valdomir con Ondra e Krasina. Li
old chef havet circum li tallia ligat un long strap, ye quel tenet se li
fugientes.

Li aqua montat e montat. Li Slavines hastat ad avan. Ma li coridor subitmen
inclinat se talmen, que ili devet marchar in aqua. Felicimen it ne durat long e
ili denove montat e marchat sur li firm terra. Ondra ja espera que li aventura
va finir bon e pro to joca con Krasina. Ma Valdomir admoni les: "`Ne di hopp
ante transsaltar.`"

E poy ili denove descendet. Ili audi li rugida del current aqua. Valdomir
halta. "`Nu, sta avan nos li max dangerosi segment de nor via. Omni deve
tener se ye li strap e tender bon li gambes. Chascun mispassu posse esser
sinistri. Ma noi es in li manu de Deo. Dunc con Su auxilie ad avan!`"

Ili ha intrat in li aqua quel curret rapidmen in li tunel. Li canes devet ja
svimmar. Li aqua atinget ja li cintura del mannes, ma ili ne perdi li
coragie.

"`Si noi va successar in ti segment, noi posse gratular nos,`" di
Valdomir. E Ondra vide avan se un grand cataract. Ma li chef, sin perdir alcun
parol, intrat in li cadent aqua...

== Retorn in li real munde

"`Il vive!`"

Ti exclamation inductet Ondra in nor munde. Su palpebres tremet quam tis de
hom venient del obscuritá in li luce. Lentmen il aperte li ocules e astonat
circumspecta. Il jace proxim li caverne in quel il ha refugit ante su cade in
li subterrania.

"`Trincar!`" susurra su arid labies. Complesent manus presenta le li
refriscant aqua quel Ondra avidmen trinca. Poy il efortia levar se, ma il senti
dolore in su tot corpore. Li regard sur li manus monstra le, que ili es plen de
contusiones. Li corpor es quam disruptet...

"`Quietá, amico,`" di le un svelt yun mann, "`noi va transportar
vos in li hospital in Blansko.`"

Mult complesent manus prepara portuore, sur quel ili cuidosimen posit Ondra
e transportat le a Blansko.

Li medicos ha constatat que ondra ne ha subeat plu grav vulneration. Li
contusiones va esser resanat durant un seman.

Pos un refriscant dormida Ondra ha aprendet que Dr Absolon trovat le in li
subterrania de Carst. On devet exportar le sur funiculari scale, quo certmen
esset tre penibil in ti strett apertura.

Quande il ha posset abandonar li lette, il hastat a su matre quel ja esset
plen de timore pri su fate, pro que il tam long ne ha venit.

Li matre balansat li cap quande Toník narrat su aventuras in li imbosca e
pri li vive in li subterrania.

"`No, Toník, tu solmen somniat to. Tu ya esset solmen un seman ex li dom
e de ti seman tu esset six dies in li hospital.`"

Ondra infidentmen regarda li matre, torna li cap e di:

"`Null somnie, mamá. Yo va adducter vos mi Krasina.`"

"`Yo vell desirar te it, mi car boy, ma specta in li calendare. Tu ha
exeat mercurdí li ninesim august e hodie noi have li decisettesim.`"

Ti explication vell convicter chascun, ma Toník ne ha esset convictet. Il eat
al cancelaria del usine, u on ja havet raport pri su accidente, e pro to on
acceptat su excusa e permisset le venir al labor lunedí. De ta il hastat al
grotte por trovar Dr Absolon e mersiar le pro li salvation.

"`Vu mem ne save, qualmen vu ha servit me, amico,`" dit Dr Absolon, li
explorator del Carst. "`Per vor cade vu ha apertet un nov via in li
subterrania del Carst. Adver noi deve ancor adaptar it e far it viabil. To va
exiger ancor mult labor.`"

Ondra narrat a Dr Absolon su aventura in li subterrania e petit Dr Absolon
prender le ad infra pro que il deve trovar su Krasina. Dr Absolon escutat con
grand interesse, ma poy il tornat li cap e dit: "`No, amico, tam long null
popul vell posser viver sin li sole. It esset solmen un somnie. Forsan un bell
somnie, ma tamen solmen un somnie.`"

"`Ma qualmen on posse somniar pri tam logic religion del Slavine? Li
somnies es ja sempre caotic.`"

"`Forsan vu ha leet alquo del sved scientist e theolog Swedenborg. Il ha
scrit pri tal coses.`"

Ondra rememora que il have li libre "`Li ver cristian religion`" de
Emanuel Swedenborg. Qualmen il ha posset obliviar ti libre quel ha impresset le
tam profundmen? Ma malgré to il retornat deceptet.

In li proxim ocasion il denova ataca Dr Absolon per questiones ca il ha
trovat alcun tracie del Slavines. Li responses nequande posset contentar
le.

Depos ti tempor Ondra esset quelcvez in li subterrania. Ma benque mult
grottes aparet le conosset, Tamen il nequande trovat su Krasina.

== Posparol del editoria

Desde li aventura de Ondra ha passat ja circa quarant annus. Durant ti
tempore li explorationes del Moravian Carst ha tre progresset. On ne solmen
decovrit mult magnific grottes, ma anc fat les accessibil per comod vias
electrificat.

Li exploration exiget anc mult pena e labor fysic. On devet ingagear mem
scafandres e automatic pumpes e sovente anc dynamit devet auxiliar por junter
li grottes e far li via al abyss Macocha (Matsokha = step-matre). Ti penibil e
expensiv labor es ja coronat, nam on posse dir, que li abyss Macocha con li
grottes apartene al max grand marveles del natura in li munde.

Li abyss es in realitá un anteyan colossal grotte (profun 138.4 m, larg 76 e
long 175 m), de quel li
plafon ha ruit e talmen ha format se li gigantic abyss. Ante li labores
mentionat on posset atinger li fude de Macocha solmen per un ferrin scale, ma
nu on posse atinger it comodmen per coridores del grottes de Punkva.

Ma ne solmen li grottes de Punkva, anc li vicin grottes de Caterina
(Kateřinské) e li splendid grotte de Masaryk fa un impression quel on ne posse
obliviar. Anc pri li labyrint-grottes de Sloup e Šosůvka e pri li grottes de
Ostrov on posse parlar solmen con superlatives.

Noi ha dit que li explorationes de Moravian Carst es ja presc finit, ma
recentmen on ha decovrit un nov subterran labyrint proxim Boskovice.

Omni ti ovres del natura merite esser videt. Li marveles es plu bell quam
posset racontar li simplic ovrero Ondra. Ili es plu bell, plu splendid, plu
magnific quam on posse imaginar.
